import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { Modal } from '../../components/ui/Modal';
import { SegmentedLevel } from '../../components/ui/SegmentedLevel';
import { StarRating } from '../../components/ui/StarRating';
import type { Film, FilmReview } from '../../types/domain';
import { saveFilmReview, updateFilmReview } from './films';
import { filmReviewMetrics, metricLevel } from './reviewMetrics';

export function FilmReviewForm({film,review,onClose}:{film:Film;review?:FilmReview;onClose:()=>void}){const qc=useQueryClient();const [rating,setRating]=useState(review?.rating??4);const [metrics,setMetrics]=useState<Record<string,number>>(()=>Object.fromEntries(filmReviewMetrics.map(metric=>[metric.key,review?.metrics?.[metric.key]??3])));const mutation=useMutation({mutationFn:(form:FormData)=>{const input={rating,comment:String(form.get('comment'))||undefined,watchedOn:String(form.get('watchedOn')),metrics};return review?updateFilmReview(film.id,review.id,input):saveFilmReview(film.id,input)},onSuccess:async()=>{await Promise.all([qc.invalidateQueries({queryKey:['film',film.id]}),qc.invalidateQueries({queryKey:['films']})]);onClose()}});return <Modal onClose={onClose}><form onSubmit={event=>{event.preventDefault();mutation.mutate(new FormData(event.currentTarget))}}><p className="eyebrow">{review?'EDITAR RESEÑA':'NUEVA VISTA'}</p><h2>{film.title}</h2><label className="film-rating">¿Cuánto te gustó?<StarRating label="Puntuación de la película" value={rating} onChange={setRating}/></label><fieldset className="film-metric-fields"><legend>¿Cómo fue la película?</legend>{filmReviewMetrics.map(metric=><div className="film-metric-field" key={metric.key}><div><strong>{metric.label}</strong><small>{metricLevel(metric.levels,metrics[metric.key])}</small></div><SegmentedLevel label={metric.label} levels={metric.levels} value={metrics[metric.key]} onChange={value=>setMetrics(current=>({...current,[metric.key]:value}))}/></div>)}</fieldset><label>Fecha en que la viste<input name="watchedOn" type="date" defaultValue={review?.watchedOn??new Date().toLocaleDateString('sv-SE')} required/></label><label>Reseña<textarea name="comment" defaultValue={review?.comment} placeholder="¿Qué cambió esta vez?"/></label><button className="main-button" disabled={mutation.isPending}>{mutation.isPending?'Guardando…':review?'Guardar cambios':'Guardar nueva reseña'} ✦</button>{mutation.error&&<p className="form-error">{mutation.error.message}</p>}</form></Modal>}
